# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: ko-KR

# Site title
title: Deep Learning Paper Reviews

# Site tagline
tagline: 딥러닝 논문 리뷰 블로그

# Site description
description: 최신 딥러닝 논문을 리뷰하고 정리합니다

# Site URL
url: "https://suholee0.github.io"
baseurl: ""

# Avatar/Profile image (사이드바 프로필 이미지)
avatar: "/assets/img/profile.png"  # 이미지 파일 경로

# GitHub username
github:
  username: suholee0

# Twitter username
twitter:
  username: # twitter username

# Social
social:
  name: Suho Lee
  email: lsw4221@gmail.com
  links:
    - https://github.com/suholee0

# Timezone
timezone: Asia/Seoul

# Pagination
paginate: 10

# The base URL of your site
permalink: /posts/:title/

# Collections
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Comments (optional - Disqus, Utterances, Giscus 등 선택 가능)
comments:
  active: giscus # 또는 disqus, utterances
  giscus:
    repo: suholee0/suholee0.github.io # GitHub 레포지토리
    repo_id: # Giscus 설정시 자동 생성
    category: Announcements
    category_id: # Giscus 설정시 자동 생성

# Analytics (optional)
google_analytics:
  id: # Google Analytics ID

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax # 수식 지원

# Collections for paper reviews
collections:
  papers:
    output: true
    permalink: /papers/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      math: true
  - scope:
      path: ""
      type: papers
    values:
      layout: post
      comments: true
      toc: true
      math: true